### PR TITLE
Add initial Gulp workflow

### PR DESCRIPTION
**Pull request by macburgee1**
- Remove all unnecessary directories and files
- Create Node.js project
- Install Gulp and related packages
- Configure SASS Gulp workflow

### CODE REVIEW

**Comment by skoolbus39** [comment]
We need to update Node/npm in DCF:
> Unsupported engine for dcf@1.0.0: wanted: {"node":"node >= 0.10.0"} (current: {"node":"13.0.1","npm":"6.12.0"})
> Not compatible with your version of node/npm: dcf@1.0.0

**Comment by macburgee1** [comment]
I think the `engines` syntax in the dcf node.js project is incorrect.

Current:
```
  "engines": {
    "node": "node >= 0.10.0"
  },
```

Per docs (https://docs.npmjs.com/files/package.json#engines):
```
  "engines" : { 
    "node" : ">= 0.10.0"
  }
```

**Comment by skoolbus39** [comment]
I don't remember writing it that way, but sure enough it's right there in the [very first commit](https://github.com/d-c-n/dcf/commit/6cf2d602026a2acc66f22c48557f1d2b1fbc90d5#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R51).

**Comment by macburgee1** [comment]
The NPM issue was fixed: d-c-n/dcf#319.
This is PR is ready for review.

**Pull request merged**
